### ISSUE TITLE
Legend: plotIndiv overrides levels of factor

### ISSUE THREAD

**Issue by KathyRuggiero** [mixOmicsTeam/mixOmics#15]
Notice that the levels of the factor "Family" in the des.df data.frame are 1, 2, ..., 10, in that order. However, plotIndiv() ignores this and reorders the levels as 1,10,2,3,...,9. Can this be corrected?

`
des.df$Family <- factor(des.df$Family, levels = 1:10) 

levels(des.df$Family)  
[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" 

plotIndiv(pca.result, ind.names = FALSE,
   group = des.df$Treatment, pch = des.df$Family,
   legend = TRUE, legend.title = 'CO2 Treatment',  
   legend.title.pch = "Family")
`

**Comment by frohart** [comment]
Hi there,

This happens because the levels of the pch factor (or the pch.levels input) are read as characters and not numbers. This is a choice that has been made to standardise the different plotting style.

However, this is only a "problem" in the ordering of the legend, not in the actual representation of the data 
```
data(breast.tumors)
X <- breast.tumors$gene.exp
Y <- breast.tumors$sample$treatment

acp = pca(X)

pch.input = c(rep(1:11,4),1,2,3)
plotIndiv(acp,ind.names=FALSE,pch=pch.input, legend=T)

quartz()
levels = letters[1:11]
pch.levels=levels[pch.input]
plotIndiv(acp,ind.names=FALSE,pch=pch.input,pch.levels=pch.levels, legend=T)
# same plot, different order of the legend
```

**Comment by KathyRuggiero** [comment]
Hi Florian,

Thanks for getting back to me so quickly. Yes, I can see that the problem is only in the ordering…and I see your solution. I’ll give it a go later!

Cheers,
Kathy

**Comment by aljabadi** [comment]
Hi, I trust that Florian's answer resolved your issue so I'm closing this.

**Comment by KathyRuggiero** [comment]
Honestly? No. But only because I really didn’t understand his answer. And I didn’t have time to follow up on it.

**Comment by aljabadi** [comment]
Sorry, there was no more followup so I assumed it was resolved.
Please download the latest development version from _devel_ branch using the instructions in `README` file and you should get the result you want. You can test it using the following code:
```
library(mixOmics)
data(multidrug)
multidrug$cell.line$Class
pca.res <- pca(multidrug$ABC.trans, ncomp = 4, scale = TRUE)
# plot(pca.res)
mypch=as.numeric(as.factor(multidrug$cell.line$Class))+3
mygroup <- rep(LETTERS[1:4],15)
plotIndiv(pca.res,pch=mypch, group=mygroup,legend = TRUE, legend.title.pch = "my pch", legend.title = "my group")
```

**Comment by aljabadi** [comment]
in case you need help on how to install the development version, you can run this:

```
if(requireNamespace('devtools')){
  installed.packages('devtools')
}
install_github("mixOmicsTeam/mixOmics", ref="devel")
```
I'll keep this issue open in case you have further questions.

**Comment by billy-s-lab** [comment]
Hello, 

I am still encountering this error in mixOmics. I create a list of mRNA and metabolomics data, define the Y factor, and run Diablo analysis as follows:

X <- list(mRNA = gene_counts,
          metab = metab_counts)
Y <- group_factor
list.keepX <- list(mRNA = c(500, 500),metab = c(50, 50))
MyResult.diablo <- block.splsda(X, Y, keepX=list.keepX, ncomp = 4)

When I plot the results using the plot function the factor grouping is correct: 
plot(MyResult.diablo)
![image](https://user-images.githubusercontent.com/59927324/82074803-359d7980-96d3-11ea-8e44-fafe2dad1389.png)

However, when I use the plotIndiv function to plot the results, the labelling by sample number is correct but the levels in the figure legend are incorrect:
plotIndiv(MyResult.diablo, 
          ind.names = TRUE, style = "ggplot2",
          legend=TRUE, cex=c(4,4,4,4),
          title = 'Sample Number Correct, Legend Group Incorrect')

The legend should read: blue = SD, orange = SHAM, grey = RYGB, green = RYGB_BMT
![image](https://user-images.githubusercontent.com/59927324/82074949-6bdaf900-96d3-11ea-84a7-4ad7782580f2.png)

I try to work around this as suggested above but then all data points disappear from the plot:
pch.input = as.numeric(as.factor(Y)) #4 level factor
#looks like: 4 3 3 2 4 2 2 3 4 4 4 4 3 2 2 4 3 3 4 2 3 3 3 1 1 1 1 1
levels = letters[1:4]
pch.levels = levels[pch.input] #4 level factor
#looks like:  "d" "c" "c" "b" "d" "b" "b" "c" "d" "d" "d" "d" "c" "b" "b" "d" "c" "c" "d" "b" "c" "c" "c" "a" "a" "a" "a" "a"

plotIndiv(MyResult.diablo, 
          ind.names = FALSE, style = "ggplot2",
          legend=TRUE, cex=c(4,4,4,4), pch = pch.input, group = pch.levels,
          title = 'No Data Points Show When Try to Correct the Legend Order')

![image](https://user-images.githubusercontent.com/59927324/82075159-bc525680-96d3-11ea-8c73-468c302b9038.png)

I have also tried saving the plotIndiv output as a ggplot2 object and overriding the figure legend but can't figure out a way to do this.

Any help/advice greatly appreciated.

Thank you very much.

**Comment by aljabadi** [comment]
Hi @billy-s-lab,

Thanks for reporting this issue. We witnessed a similar issue after the latest updates to dependencies. 

However, I cannot reproduce your error using mixOmics data. It would be great if you could reproduce it using our examples. Alternatively, you can email us your code + data in confidentiality so I can reproduce and fix it. [You can click on this text to send us an email](mailto:mixomics@math.univ-toulouse.fr). Alternatively, you can right-click on the above text and choose ‘Copy Email Address’.

Best,

Al

**Comment by aljabadi** [comment]
I added a fix similar to a solution that debugged a previous issue. Can you please update to the [latest GitHub devel](https://github.com/mixOmicsTeam/mixOmics#development-version) and see if it resolves the issue first.

Let me know if it works or if you keep having the issue.

Best,

Al

**Comment by billy-s-lab** [comment]
Hi Al, 
Thanks a lot for your help. I installed the latest version and it seems to have corrected the issue - please see sample plot below. Sample numbers and groups are correct.
![image](https://user-images.githubusercontent.com/59927324/82380045-c51e9180-9a1f-11ea-97a2-8fbb2a58e0c6.png)

The legend order is not the way I would like it and seems to be following the alphabetical order of the groups.
I changed it doing the below:
a <- plotIndiv(MyResult.diablo, 
          ind.names = TRUE, style = "ggplot2",
          legend=TRUE, cex=c(4,4,4,4),
          title = 'Sample Number Correct, Legend Group \nNow Correct')
b <- a$graph
b+scale_color_manual(breaks=c("SD","SHAM" ,"RYGB", "RYGB_BMT"), values = c("#388ECC","#F68B33","#C2C2C2","#009E73"))+
  labs(color = "Group")

![image](https://user-images.githubusercontent.com/59927324/82380372-41b17000-9a20-11ea-8012-d8a96454bce0.png)


Not sure if you have a better way of ordering the figure legend in plotIndiv or if it's better to save it as a ggplot object and modify it this way.

Thanks again for your help.
